use jar url instead of file path on lambda deploy

diff --git a/.github/workflows/upload-release-assets.yml b/.github/workflows/upload-release-assets.yml
--- a/.github/workflows/upload-release-assets.yml
+++ b/.github/workflows/upload-release-assets.yml
@@ -6,6 +6,57 @@ on:
 
 jobs:
 
+  publish-zoe-core-jar:
+    name: Publis zoe core jar
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: '100'
+
+      - name: set upload url
+        id: fetch_release_data
+        run: |
+          UPLOAD_URL=$(jq -r '.release.upload_url' ${GITHUB_EVENT_PATH})
+          echo "::set-output name=upload_url::$UPLOAD_URL"
+
+      - name: Setup Java JDK
+        uses: actions/setup-java@v1.3.0
+        with:
+          java-version: 11
+          java-package: jdk
+          architecture: x64
+
+      - name: Build
+        run: ./gradlew clean zoe-core:shadowJar
+
+      - name: Package
+        id: package
+        run: |
+          ./dev/scripts/packages-without-runtime.sh
+
+          # retrieve jar
+          zoe_jar_path=$(ls -t zoe-core/build/libs/zoe-core-*.jar | head -n 1)
+
+          # ensure jar is generated
+          [[ -z "${zoe_jar_path}" ]] && \
+            { echo "zoe core jar not found : ${zoe_jar_path}"; exit 1; }
+
+          echo "::set-output name=zoe_jar_path::${zoe_jar_path}"
+          echo "::set-output name=zoe_jar_name::$(basename ${zoe_jar_path})"
+
+      - name: Upload zip package
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.fetch_release_data.outputs.upload_url }}
+          asset_path: ${{ steps.package.outputs.zoe_jar_path }}
+          asset_name: ${{ steps.package.outputs.zoe_jar_name }}
+          asset_content_type: application/zip
+
   release-runtimeless:
     name: Publish packages without runtime
 
